# Dockerfile

# Build stage
FROM node:18 AS build

WORKDIR /app

# Copy package.json to install dependencies
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Build the Next.js application
RUN npm run build

# Production stage
FROM node:18 AS production

WORKDIR /app

# Copy everything from the build stage
COPY --from=build /app /app

# Expose the port that the app runs on
EXPOSE 3000

# Start the server
CMD ["npm", "run", "start"]


