# Dockerfile

# Build stage
FROM node:18 AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# Build the Next.js application, without exporting it statically
RUN npm run build

# Production stage
FROM node:18 AS production

WORKDIR /app

COPY --from=build /app /app

# Expose the port that the app runs on
EXPOSE 3000

# Start the server
CMD ["npm", "run", "start"]

