version: '3'

services:
  backend:
    image: your_azure_artifact_repo/backend:latest  # Replace with your actual backend image path
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - app-network

  frontend:
    image: your_azure_artifact_repo/frontend:latest  # Replace with your actual frontend image path
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
