version: '3'
 
services: 
  backend:  
    image: shreyas3799.azurecr.io/backend:v45  # Replace with your actual backend image path
    container_name: backend
    ports:
      - "8080:8080"
    environment:   
      - PORT=8080
    networks:
      - app-network

  frontend:
    image: shreyas3799.azurecr.io/frontend:v44  # Replace with your actual frontend image path
    container_name: frontend
    ports:
      - "80:3000"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
