apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <ACR_LOGIN_SERVER>/backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: MONGODB_URI
          value: "<MONGODB_URI>"
        - name: FRONTEND_URL
          value: "http://<VM_PUBLIC_IP>:3000"
        - name: JWT_SECRET
          value: "<JWT_SECRET>"
        imagePullPolicy: Always
