apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # Number of additional pods that can be created during the update
      maxUnavailable: 1 # Number of pods that can be unavailable during the update
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: acr-secret # Reference the Kubernetes secret for ACR authentication
      containers:
      - name: frontend
        image: <ACR_LOGIN_SERVER>/frontend:latest # Replace with actual ACR login server
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://<VM_PUBLIC_IP>:30080" # Replace <VM_PUBLIC_IP> with the public IP of your VM
        - name: NEXT_PUBLIC_AUTH_URL
          value: "http://<VM_PUBLIC_IP>:30080" # Replace <VM_PUBLIC_IP> with the public IP of your VM
        imagePullPolicy: Always
