---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30030  # NodePort inside the Kind container
        hostPort: 30030       # Host machine port mapping
        protocol: TCP
      - containerPort: 30080  # NodePort inside the Kind container
        hostPort: 30080       # Host machine port mapping
        protocol: TCP
