kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30030 # The NodePort inside the Kind container
    hostPort: 30030      # Map this to the same port on the host machine
    protocol: TCP
  - containerPort: 30080 # The NodePort inside the Kind container
    hostPort: 30080      # Map this to the same port on the host machine
    protocol: TCP
