apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  type: ClusterIP  # Default type, internal only
  selector:
    app: backend
  ports:
  - port: 8080         # Internal service port
    targetPort: 8080   # Target port on the container
