
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-replicaset
  namespace: backend-namespace
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: backend-image:latest
        ports:
        - containerPort: 5000
