
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  namespace: backend-namespace
  labels:
    app: backend
spec:
  containers:
    - name: backend-container
      image: backend-image:latest
      ports:
        - containerPort: 5000
