apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # Port exposed within the cluster
      targetPort: 3000      # Port on the container
      nodePort: 30080     # Exposes this service on port 30080 for external access
  type: NodePort
