apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80           # Internal cluster port
      targetPort: 3000    # Port on the container your app listens to
  type: ClusterIP         # Restrict service to cluster-only access
