apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shreyas3799.azurecr.io/frontend:v1  # Image updated via pipeline
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_SERVICE_URL
              value: "http://backend-service.backend.svc.cluster.local:5000"  # Internal URL for backend
      imagePullSecrets:
        - name: acr-auth
