
apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  namespace: frontend-namespace
  labels:
    app: frontend
spec:
  containers:
    - name: frontend-container
      image: frontend-image:latest
      ports:
        - containerPort: 80
