
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-replicaset
  namespace: frontend-namespace
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: frontend-image:latest
        ports:
        - containerPort: 80
