apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shreyas3799.azurecr.io/frontend:v35  # Replace with your frontend image URL
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://backend-service.backend.svc.cluster.local:8080"  # Internal DNS for backend service
      imagePullSecrets:
      - name: acr-secret
