apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shreyas3799.azurecr.io/frontend:v52  # Image updated via pipeline
          ports:
            - containerPort: 80  # Updated to match Docker image's exposed port
          env:
            - name: BACKEND_SERVICE_URL
              value: "http://backend-service.backend.svc.cluster.local:5000"  # Internal URL for backend service
          livenessProbe:
            httpGet:
              path: /
              port: 80  # Matches the exposed port in Docker image
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80  # Matches the exposed port in Docker image
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: acr-auth
