name: Combined CI/CD Pipeline

on:
  push:
    branches:
      - shreyas
    paths:
      - 'frontend/**'
      - 'backend/**'
  workflow_dispatch:
    description: "Manually trigger the combined CI/CD pipeline"

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read

# These environment variables are used by the terraform azure provider to setup OIDC authentication.
env:
  ARM_USE_OIDC: "true"
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  JWT_SECRET: "${{ secrets.JWT_SECRET }}"
  MONGODB_URI: "${{ secrets.MONGODB_URI }}"

jobs:
  backend_test:
    name: Test and Validate Backend Docker Container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies for Backend
      run: npm install
      working-directory: backend

    - name: Run Backend Unit Tests
      run: npm test -- --detectOpenHandles
      working-directory: backend

    - name: Install hadolint
      run: |
        curl -sL https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
        chmod +x /usr/local/bin/hadolint

    - name: Lint Dockerfiles
      run: |
        hadolint backend/Dockerfile
        hadolint frontend/Dockerfile

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: terraform

    - name: Set Up SSH Keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/id_rsa.pub

    - name: Get ACR Credentials and VM Public IP
      id: get-acr
      run: |
        echo "ACR_LOGIN_SERVER=$(terraform output -raw acr_login_server)" >> $GITHUB_ENV
        echo "ACR_USERNAME=$(terraform output -raw acr_username)" >> $GITHUB_ENV
        echo "ACR_PASSWORD=$(terraform output -raw acr_password)" >> $GITHUB_ENV
        echo "VM_PUBLIC_IP=$(terraform output -raw frontend_backend_public_ip)" >> $GITHUB_ENV
      working-directory: terraform

    - name: Login to ACR
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.ACR_LOGIN_SERVER }}
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}

    - name: Build and Push Backend Docker Image
      run: |
        docker buildx build --target development --platform linux/amd64 -t ${{ env.ACR_LOGIN_SERVER }}/backend:test ./backend
        docker push ${{ env.ACR_LOGIN_SERVER }}/backend:test

    - name: Validate Backend Docker Image
      run: |
        docker run --rm \
          -e PORT=8080 \
          -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
          -e FRONTEND_URL=http://${{ env.VM_PUBLIC_IP }}:3000 \
          -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
          ${{ env.ACR_LOGIN_SERVER }}/backend:test npm test

  deployment:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: backend_test

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: terraform

    - name: Set Up SSH Keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/id_rsa.pub

    - name: Get ACR Credentials and VM Public IP
      id: get-acr
      run: |
        echo "ACR_LOGIN_SERVER=$(terraform output -raw acr_login_server)" >> $GITHUB_ENV
        echo "ACR_USERNAME=$(terraform output -raw acr_username)" >> $GITHUB_ENV
        echo "ACR_PASSWORD=$(terraform output -raw acr_password)" >> $GITHUB_ENV
        echo "VM_PUBLIC_IP=$(terraform output -raw frontend_backend_public_ip)" >> $GITHUB_ENV
      working-directory: terraform

    - name: Login to ACR
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.ACR_LOGIN_SERVER }}
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}

    - name: Build and Push Frontend and Backend Docker Images
      run: |
        docker buildx build --target production --platform linux/amd64 -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend
        docker buildx build --target production --platform linux/amd64 -t ${{ env.ACR_LOGIN_SERVER }}/backend:latest ./backend
        docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest
        docker push ${{ env.ACR_LOGIN_SERVER }}/backend:latest

    - name: SSH into Azure VM and Deploy Docker Containers
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azureuser@${{ env.VM_PUBLIC_IP }} <<EOF

          echo ${{ env.ACR_PASSWORD }} | docker login ${{ env.ACR_LOGIN_SERVER }} -u ${{ env.ACR_USERNAME }} --password-stdin
          
          docker image prune -af

          docker pull ${{ env.ACR_LOGIN_SERVER }}/frontend:latest
          docker pull ${{ env.ACR_LOGIN_SERVER }}/backend:latest

          docker stop frontend || true && docker rm frontend || true
          docker stop backend || true && docker rm backend || true

          docker run -d --name frontend -p 3000:3000 -e NEXT_PUBLIC_API_URL=http://${{ env.VM_PUBLIC_IP }}:8080 -e NEXT_PUBLIC_AUTH_URL=http://${{ env.VM_PUBLIC_IP }}:8080 ${{ env.ACR_LOGIN_SERVER }}/frontend:latest
          docker run -d --name backend -p 8080:8080 -e PORT=8080 -e MONGODB_URI=${{ secrets.MONGODB_URI }} -e FRONTEND_URL=http://${{ env.VM_PUBLIC_IP }}:3000 -e JWT_SECRET=${{ secrets.JWT_SECRET }} ${{ env.ACR_LOGIN_SERVER }}/backend:latest
        EOF
