name: Terraform Provisioning
on:
  push:
    branches:
      - shreyas
    paths:
      - "azure-terraform/**"
  workflow_dispatch:

jobs:
  provision-infrastructure: 
    name: Provision Infrastructure with Terraform
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd azure-terraform
          terraform init

      - name: Apply Terraform Configuration
        run: |
          cd azure-terraform
          terraform apply -auto-approve

      - name: Capture Outputs
        id: capture_outputs
        run: |
          # Capture Terraform outputs and write them to a file
          echo "VM_PUBLIC_IP=$(terraform output -raw vm_public_ip)" > terraform_outputs.txt
          echo "ACR_LOGIN_SERVER=$(terraform output -raw acr_login_server)" >> terraform_outputs.txt

      - name: Upload Outputs as Artifacts
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: terraform-outputs
          path: terraform_outputs.txt

  update-secrets:
    name: Update GitHub Secrets with Terraform Outputs
    runs-on: ubuntu-latest
    needs: provision-infrastructure
    steps:
      - name: Download Outputs Artifact
        uses: actions/download-artifact@v3  # Updated to v3
        with:
          name: terraform-outputs

      - name: Update GitHub Secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Read outputs from the artifact file and update secrets
          while IFS= read -r line; do
            key=$(echo $line | cut -d '=' -f 1)
            value=$(echo $line | cut -d '=' -f 2)
            echo "Updating secret $key..."
            curl -X PUT -H "Authorization: Bearer $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/actions/secrets/$key \
                 -d "{\"encrypted_value\":\"$value\"}"
          done < terraform_outputs.txt
