name: Rollback CI/CD Pipeline

on:
  push:
    branches: 
      - shreyas
    paths:
      - '**/rollback_image_cicd_pipeline.yml'
  workflow_dispatch:
    inputs:
      image_version:
        description: "Specify the image version to roll back to (e.g., v1, v2)"
        required: true
        default: "v117"

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: "true"
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  rollback:
    name: Rollback Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: terraform
    
    - name: Set Up SSH Keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/id_rsa.pub

    - name: Get ACR Credentials and VM Public IP
      id: get-acr
      run: |
        echo "ACR_LOGIN_SERVER=$(terraform output -raw acr_login_server)" >> $GITHUB_ENV
        echo "ACR_USERNAME=$(terraform output -raw acr_username)" >> $GITHUB_ENV
        echo "ACR_PASSWORD=$(terraform output -raw acr_password)" >> $GITHUB_ENV
        echo "VM_PUBLIC_IP=$(terraform output -raw frontend_backend_public_ip)" >> $GITHUB_ENV
      working-directory: terraform

    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq

    - name: Replace Variables in YAML Files
      run: |
        yq eval ".spec.template.spec.containers[0].image = \"${{ env.ACR_LOGIN_SERVER }}/frontend:${{ github.event.inputs.image_version }}\"" -i k8s/deployment-frontend.yaml
        yq eval ".spec.template.spec.containers[0].image = \"${{ env.ACR_LOGIN_SERVER }}/backend:${{ github.event.inputs.image_version }}\"" -i k8s/deployment-backend.yaml

    - name: Login to ACR
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.ACR_LOGIN_SERVER }}
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}

    - name: Configure ACR Secret in Kubernetes
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azureuser@${{ env.VM_PUBLIC_IP }} <<EOF
          kubectl delete secret acr-secret --ignore-not-found  # Remove existing secret if any
          kubectl create secret docker-registry acr-secret \
            --docker-server=${{ env.ACR_LOGIN_SERVER }} \
            --docker-username=${{ env.ACR_USERNAME }} \
            --docker-password=${{ env.ACR_PASSWORD }} \
            --docker-email=old_user_1468642@seneca-caa900naa.cloudlabs.ai
        EOF

    - name: Rollback Kubernetes Resources
      run: |
        scp -i ~/.ssh/id_rsa k8s/*.yaml azureuser@${{ env.VM_PUBLIC_IP }}:/home/azureuser/
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azureuser@${{ env.VM_PUBLIC_IP }} <<EOF
          kubectl apply -f /home/azureuser/deployment-frontend.yaml
          kubectl apply -f /home/azureuser/service-frontend.yaml
          kubectl apply -f /home/azureuser/deployment-backend.yaml
          kubectl apply -f /home/azureuser/service-backend.yaml
        EOF

    - name: Confirm Rollback
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azureuser@${{ env.VM_PUBLIC_IP }} <<EOF
          kubectl rollout status deployment/frontend-deployment
          kubectl rollout status deployment/backend-deployment
        EOF
