name: Validate All Files

on:
  push:
    branches:
      - main
      - shreyas
    paths:
      - '**/*.yaml'
      - '**/Dockerfile'
      - '**/*.js'
      - '**/*.ts'
      - '.github/workflows/*.yml'
      - 'terraform/**'
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/Dockerfile'
      - '**/*.js'
      - '**/*.ts'
      - '.github/workflows/*.yml'
      - 'terraform/**'

jobs:
  validate:
    name: Validate All Configurations and Scripts
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Validation Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y yamllint shellcheck
        curl -fsSL https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz | tar -xzvf -
        sudo mv kubeval /usr/local/bin/
        curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64"
        chmod +x ./kind && sudo mv ./kind /usr/local/bin/
        curl -fsSL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
        chmod +x /usr/local/bin/hadolint
        curl -fsSL https://raw.githubusercontent.com/hashicorp/terraform-ls/main/install.sh | bash
        npm install -g eslint

    - name: Validate Kubernetes YAML Files
      run: |
        yamllint k8s/*.yaml
        kubeval --ignore-missing-schemas k8s/*.yaml

    - name: Lint Dockerfiles
      run: |
        hadolint backend/Dockerfile frontend/Dockerfile

    - name: Test Workflows Locally
      run: |
        curl -fsSL https://github.com/nektos/act/releases/latest/download/act_Linux_x86_64.tar.gz | tar -xzvf -
        sudo mv act /usr/local/bin/
        act -l  # List workflows
        act -P ubuntu-latest=catthehacker/ubuntu:act-latest  # Specify image explicitly

        
    - name: Validate Terraform Files
      run: |
        terraform fmt -check -recursive
        terraform validate

    - name: Lint JavaScript/TypeScript Files
      run: |
        eslint backend/**/*.js backend/**/*.ts frontend/**/*.js frontend/**/*.ts

    - name: Validate Shell Scripts
      run: |
        find . -name "*.sh" -exec shellcheck {} \;

    - name: Summary
      run: echo "Validation Workflow Complete!"
